# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    evdev:
        - step:
            name: Build and push to server
            script:
              - ssh mneme@20.232.26.254 ". ~/.nvm/nvm.sh && bash ~/CICD/frappe_run.sh"
              - echo frappe deployed!
  custom:
      prod-deploy:
      -   step:
            script:
              - apt-get update
              - apt-get install -y zip
              - apt-get install sshpass
              - sshpass -p 'frappe' ssh everest@65.21.55.189 ". ~/.nvm/nvm.sh && bash ~/CICD/frappe_run.sh"
              - echo ssh succeeded